name: Skales
description: idk
authors: [nix]
website: https://github.com/Nix-alt/Skales
api-version: '1.13'
version: 0.1.0
main: com.nix.skales.Skales
commands:
  skales:
    description: main command for the skales addon
    permission: skales.command
depend:
  - Skript  
